name: Build package

on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  test_m1:
    name: "Test M1"
    runs-on: macos-latest-xlarge
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - name: Read architecture
        id: architecture
        run: |
          set -e
          ARCH=$(uname -m)
          if [[ "$ARCH" == "x86_64" ]]; then
            ARCH="x64"
          fi
          echo "ARCH=$ARCH" >> $GITHUB_ENV
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
          architecture: ${{ env.ARCH }}
      - name: Dummy text
        run: |
          set -e
          echo $(uname -m)
          echo $ARCH